# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 510)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 311, 431))
        self.groupBox.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.LoadImage = QtWidgets.QPushButton(self.groupBox)
        self.LoadImage.setGeometry(QtCore.QRect(10, 30, 291, 41))
        self.LoadImage.setAutoDefault(False)
        self.LoadImage.setDefault(False)
        self.LoadImage.setObjectName("LoadImage")
        self.ShowImages = QtWidgets.QPushButton(self.groupBox)
        self.ShowImages.setGeometry(QtCore.QRect(10, 100, 291, 41))
        self.ShowImages.setAutoDefault(False)
        self.ShowImages.setDefault(False)
        self.ShowImages.setObjectName("ShowImages")
        self.SD = QtWidgets.QPushButton(self.groupBox)
        self.SD.setGeometry(QtCore.QRect(10, 170, 291, 41))
        self.SD.setAutoDefault(False)
        self.SD.setDefault(False)
        self.SD.setObjectName("SD")
        self.SMS = QtWidgets.QPushButton(self.groupBox)
        self.SMS.setGeometry(QtCore.QRect(10, 240, 291, 41))
        self.SMS.setAutoDefault(False)
        self.SMS.setDefault(False)
        self.SMS.setObjectName("SMS")
        self.SC = QtWidgets.QPushButton(self.groupBox)
        self.SC.setGeometry(QtCore.QRect(10, 310, 291, 41))
        self.SC.setAutoDefault(False)
        self.SC.setDefault(False)
        self.SC.setObjectName("SC")
        self.Inference = QtWidgets.QPushButton(self.groupBox)
        self.Inference.setGeometry(QtCore.QRect(10, 380, 291, 41))
        self.Inference.setAutoDefault(False)
        self.Inference.setDefault(False)
        self.Inference.setObjectName("Inference")
        self.Image = QtWidgets.QGraphicsView(Form)
        self.Image.setGeometry(QtCore.QRect(360, 120, 260, 260))
        self.Image.setObjectName("Image")
        self.Label = QtWidgets.QLabel(Form)
        self.Label.setGeometry(QtCore.QRect(360, 390, 261, 30))
        self.Label.setText("")
        self.Label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.Label.setObjectName("Label")
        self.Demo = QtWidgets.QComboBox(Form)
        self.Demo.setGeometry(QtCore.QRect(520, 30, 101, 25))
        self.Demo.setObjectName("Demo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CVDL 2022 HW2"))
        self.groupBox.setTitle(_translate("Form", "5. ResNet50"))
        self.LoadImage.setText(_translate("Form", "Load Image"))
        self.ShowImages.setText(_translate("Form", "1. Show Images"))
        self.SD.setText(_translate("Form", "2. Show Distribution"))
        self.SMS.setText(_translate("Form", "3. Show model Structure"))
        self.SC.setText(_translate("Form", "4. Show Comparison"))
        self.Inference.setText(_translate("Form", "5. Inference"))
